import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#31101e",
        "primary-fixed-dim": "#91d963",
        "secondary-fixed-dim": "#b5ccc0",
        "on-background": "#191c1d",
        "on-secondary": "#191c1d",
        "on-primary-fixed-variant": "#225100",
        "tertiary-container": "#ffc5d7",
        "surface-container-low": "#f2f4f5",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#0b1f18",
        "on-surface": "#191c1d",
        "tertiary-fixed-dim": "#f0b7c9",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#092100",
        "error-container": "#ffdad6",
        "surface-container": "#eceeef",
        "primary": "#9fe870",
        "outline-variant": "#c1cab5",
        "background": "#f8fafb",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#9fe870",
        "tertiary": "#7e5161",
        "surface-tint": "#9fe870",
        "surface-dim": "#d8dadb",
        "on-secondary-container": "#54695f",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#ffd9e3",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#7b4f5e",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f2",
        "on-primary": "#092100",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8e9",
        "secondary-fixed": "#d0e8dc",
        "secondary-container": "#d0e8dc",
        "surface-bright": "#f8fafb",
        "primary-fixed": "#acf67c",
        "on-tertiary-fixed-variant": "#643a49",
        "outline": "#717a68",
        "secondary": "#4e6359",
        "inverse-primary": "#91d963",
        "on-surface-variant": "#41493a",
        "surface": "#f8fafb",
        "on-primary-fixed": "#092100",
        "on-secondary-fixed-variant": "#374b42",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
};
